import Head from 'next/head'
import {useEffect} from "react";
import {MyComponent, defineCustomElements, applyPolyfills} from "../components/stencils";

import styles from '@/styles/Home.module.css'

// No hydration error but causes inner html to be rendered twice
defineCustomElements();

export default function Home() {
  // Hydration error:
  // useEffect(() => {
  //   applyPolyfills().then(() => {
  //       defineCustomElements();
  //   });
  // });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <my-component first="Your" last="Name" />
      </main>
    </>
  )
}